### ISSUE TITLE
As a shopper, I can view a Homepage

### ISSUE THREAD

**Issue by stephenrichter** [BASE1com/flex-storefront#1]
App opens to a homepage with clear navigation and feature products that kickstart the users shopping journey.

## Description
The homepage is the front door to Flex Storefront, as well as a **navigational anchor** and **safe fallback**.

It’s critical the homepage makes it clear how the user can pursue **3 primary product-finding paths**:
1. Category Navigation
2. Search
3. Curated Paths (guides, new arrivals, etc.)

It’s also an opportunity to shape user perceptions and answer 3 vital questions:
1. What type of app is this?
2. What can I do with this app?
3. What should I expect to find?

## Wireframe

_Note: In Alpha stages, wireframes may not be exact representations of acceptance criteria or final implementations_

![Image](https://github.com/BASE1com/flex-storefront/assets/3759863/fe30e4a2-e44e-412f-b1e2-d3e98ac00dcb)

**Comment by stephenrichter** [comment]
For MVP, the Homepage should provide the following sections ft. Flex UI widgets:
- Carousel (setup via CMS)
- Category Tiles (horizontal scroll view)
- Recently Viewed or Popular Products (product cards)

**Comment by ncuillery** [comment]
- [x] ImageCarrousel (agnostic about what the image is, product or category)
- [x] Text Header
- [x] ProductCarrousel (with hardcoded data until we have our backend, but that would be the "Recently Viewed" or "Popular Products")
- [ ] ImageBanner with a attribute fullWidth true/false
- [x] eventually a vertical Spacing element

**Comment by stephenrichter** [comment]
The basic HomePage functionality now exists with the latest release 2211.1.0
